name: Deploy Flet App to GitHub Pages

on:
  push:
    branches: [ main ] # Dispara o build sempre que você der push na main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build Flet Web
        run: |
          # O segredo: o build roda em um ambiente linux limpo
          poetry run flet build web src --base-url /ETEMAC-CALCULADORA-FREQUENCIA/

      - name: Add .nojekyll
        run: touch src/build/web/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: src/build/web # A pasta que o Action vai "transplantar" sozinha
          branch: gh-pages      # A branch de destino
